spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev                    #开发环境
  application:
    name: microservicecloud-config-mflood-dev
---
spring:
  profiles: test                    #开发环境
  application:
    name: microservicecloud-config-mflood-test
#必须以UTF-8的格式保存