spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001
spring: 
   profiles: dev
   application: 
    name: microservicecloud-config-dept-client
   datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource                           # 当前数据源操作类型
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver        # mysql驱动包
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=clouddb01
    username: sa
    password: 1
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mflood.springcloud.rest.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: mflood-microservicecloud-springcloudconfig01
  company.name: www.mflood.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring: 
   profiles: test
   application: 
    name: microservicecloud-config-dept-client
   datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource                           # 当前数据源操作类型
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver        # mysql驱动包
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=clouddb02
    username: sa
    password: 1
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200  
  
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mflood.springcloud.rest.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: mflood-microservicecloud-springcloudconfig02
  company.name: www.mflood.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
 